### ISSUE TITLE
Use linked list instead of arrray for storing runs

### ISSUE THREAD

**Issue by Pawlost** [starandserpent/Foreman#8]
Linked list has same disadvantags as RLE (in terms of access) but the advantage compared to array is that it doesnt need to be rezised and allocated again. This makes it ideal for making changes in chunk and picking. There is disadvantage in terms of memory but because we are using RLE I think we can afford it.

**Comment by Pilvinen** [comment]
LinkedList has fragmented memory, but no memory copying.

No possibility to do random access as there are no indexers, always need to interate through the whole thing to find XYZ. 

Larger memory use compared to arrays - stores pointers to next, or next/previous neighbor (LinkedList\<T\>). 

Very fast constant time insertion and deletion. 

If there is no need to find next AND previous neighbor a singly linked list (as opposed to doubly linked) would use less memory, saving one pointer reference.

Might work, especially with RLE.

Otherwise (without RLE) an unsorted vector array, and swapping the element to be deleted with the last element, and then deleting the last element, would be faster.

But I think this is worth trying out.

**Comment by Pilvinen** [comment]
Ah, hm. Ok, so apparently seek time to insert/delete anywhere will be more than shifting an array based list around.

LinkedList is only quicker at inserting/deleting at the very front of it.

Iterating will be more than an order of magnitude slower due to the pointer chasing and memory overhead (no caching at all).

**Comment by Pilvinen** [comment]
![Screenshot_20200607_124511_com discord](https://user-images.githubusercontent.com/4374351/83965540-0a1a4300-a8bd-11ea-9091-2b36d576c6ec.jpg)

**Comment by Pawlost** [comment]
Seems like regular array is better. We wont use linked list so I am closing this issue.
